AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for SQS to DynamoDB Lambda Function'

Parameters:
  LambdaFunctionName:
    Type: String
    Default: SqsToDynamoDbFunction
    Description: Name of the Lambda function
  
  DynamoDBTableName:
    Type: String
    Default: SqsMessages
    Description: Name of the DynamoDB table
  
  SQSQueueName:
    Type: String
    Default: SqsMessageQueue
    Description: Name of the SQS queue
  
  LambdaMemorySize:
    Type: Number
    Default: 256
    Description: Memory size for Lambda function (MB)
  
  LambdaTimeout:
    Type: Number
    Default: 30
    Description: Timeout for Lambda function (seconds)

Resources:
  # DynamoDB Table
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      Tags:
        - Key: Application
          Value: SqsToDynamoDB

  # SQS Queue
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SQSQueueName
      VisibilityTimeout: 60
      Tags:
        - Key: Application
          Value: SqsToDynamoDB

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SqsToDynamoDbLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt SqsQueue.Arn
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt DynamoDbTable.Arn

  # Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: dotnet8
      Handler: SqsToDynamoDbLambda::SqsToDynamoDbLambda.Function::FunctionHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      Code:
        S3Bucket: DEPLOYMENT_BUCKET_NAME_TO_BE_REPLACED
        S3Key: lambda-function.zip
      Tags:
        - Key: Application
          Value: SqsToDynamoDB

  # Lambda Permission for SQS
  LambdaSqsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt SqsQueue.Arn

  # Event Source Mapping (SQS to Lambda)
  SqsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt SqsQueue.Arn
      FunctionName: !Ref LambdaFunction
      BatchSize: 10
      Enabled: true

Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
  
  SqsQueueUrl:
    Description: The URL of the SQS queue
    Value: !Ref SqsQueue
  
  SqsQueueArn:
    Description: The ARN of the SQS queue
    Value: !GetAtt SqsQueue.Arn
  
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTableName